allowBuilds:
  '@stellar/stellar-sdk': true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  msw: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@stellar/stellar-sdk'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - msw
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
